version: 2.1

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux
jobs:
  build-test-linux:
    docker:
      - image: ldcircleci/ld-c-sdk-ubuntu  # defined in sdks-ci-docker project
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
